services:
    fastapi:
        container_name: ford_falkerson_fastapi
        build:
            context: ../backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
            - "5678:5678"
        command: "debugpy --listen 0.0.0.0:5678 -m uvicorn --factory src.main:create_app --reload --host 0.0.0.0 --port 8000"
        volumes:
            - ../backend:/backend
        networks:
            - ford_falkerson_network

networks:
    ford_falkerson_network:
        driver: bridge
